
import com.sun.tools.javac.Main;
import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Checkbox;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Label;
import java.awt.LayoutManager;
import static java.awt.PageAttributes.MediaType.D;
import java.awt.TextField;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import net.miginfocom.swing.MigLayout;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author KTECH
 */
public class UI extends javax.swing.JFrame {

    LocalDateTime idt = LocalDateTime.now();

    /**
     * Creates new form UI
     */
    public UI() {

        initComponents();

        taskManager.retrieveTasksFromFile("tasks.txt");
        AddingArea.setLayout(new MigLayout("wrap"));
        AddingArea.setPreferredSize(AddingArea.getSize());

        updatePriorityUI();

        jButton2.setIcon(null);
        jButton3.addActionListener(e
                -> {
            retrieveCompletedTasksFromFile("completed_tasks.txt");
        });

        ourDateTime();

        Timer timer = new Timer(1000, (e)
                -> {
            ourDateTime();

        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Root = new javax.swing.JPanel();
        TimerPanel = new javax.swing.JPanel();
        CurrentTimer = new javax.swing.JLabel();
        TimerButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TimerAddingPanel = new javax.swing.JPanel();
        todopanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AddingPanel = new javax.swing.JPanel();
        TaskInputer = new javax.swing.JTextField();
        PrioritySetter = new javax.swing.JComboBox<>();
        AddingButton = new javax.swing.JButton();
        AddingArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("To Do App");
        setResizable(false);

        Root.setName("Root"); // NOI18N
        Root.setLayout(new java.awt.BorderLayout());

        TimerPanel.setBackground(new java.awt.Color(54, 53, 53));
        TimerPanel.setToolTipText("");
        TimerPanel.setPreferredSize(new java.awt.Dimension(500, 523));

        CurrentTimer.setText("jLabel2");

        TimerButton.setBackground(new java.awt.Color(5, 74, 145));
        TimerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hourglass.png"))); // NOI18N
        TimerButton.setMinimumSize(new java.awt.Dimension(59, 28));
        TimerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimerButtonActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(202, 60, 37));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/image.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(79, 102, 84));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/timer.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 57, 57));
        jLabel2.setText("CALENDER");

        TimerAddingPanel.setBackground(new java.awt.Color(54, 53, 53));

        javax.swing.GroupLayout TimerAddingPanelLayout = new javax.swing.GroupLayout(TimerAddingPanel);
        TimerAddingPanel.setLayout(TimerAddingPanelLayout);
        TimerAddingPanelLayout.setHorizontalGroup(
            TimerAddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        TimerAddingPanelLayout.setVerticalGroup(
            TimerAddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TimerPanelLayout = new javax.swing.GroupLayout(TimerPanel);
        TimerPanel.setLayout(TimerPanelLayout);
        TimerPanelLayout.setHorizontalGroup(
            TimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimerPanelLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(CurrentTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimerPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TimerAddingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TimerPanelLayout.createSequentialGroup()
                        .addComponent(TimerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        TimerPanelLayout.setVerticalGroup(
            TimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(TimerPanelLayout.createSequentialGroup()
                .addComponent(CurrentTimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(TimerAddingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addGroup(TimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TimerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Root.add(TimerPanel, java.awt.BorderLayout.CENTER);

        todopanel.setBackground(new java.awt.Color(76, 76, 76));
        todopanel.setPreferredSize(new java.awt.Dimension(400, 400));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TO DO LIST");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        AddingPanel.setBackground(new java.awt.Color(68, 68, 68));

        TaskInputer.setBackground(new java.awt.Color(13, 61, 121));
        TaskInputer.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        TaskInputer.setForeground(new java.awt.Color(255, 255, 255));
        TaskInputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskInputerActionPerformed(evt);
            }
        });

        PrioritySetter.setBackground(new java.awt.Color(8, 41, 84));
        PrioritySetter.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        PrioritySetter.setForeground(new java.awt.Color(255, 255, 255));
        PrioritySetter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P1", "P2", "P3", "P4" }));
        PrioritySetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrioritySetterActionPerformed(evt);
            }
        });

        AddingButton.setBackground(new java.awt.Color(105, 105, 105));
        AddingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        AddingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddingPanelLayout = new javax.swing.GroupLayout(AddingPanel);
        AddingPanel.setLayout(AddingPanelLayout);
        AddingPanelLayout.setHorizontalGroup(
            AddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddingPanelLayout.createSequentialGroup()
                .addGroup(AddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddingPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(TaskInputer, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PrioritySetter, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddingPanelLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(AddingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddingPanelLayout.setVerticalGroup(
            AddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddingPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(AddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TaskInputer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrioritySetter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        AddingArea.setBackground(new java.awt.Color(59, 72, 96));

        javax.swing.GroupLayout AddingAreaLayout = new javax.swing.GroupLayout(AddingArea);
        AddingArea.setLayout(AddingAreaLayout);
        AddingAreaLayout.setHorizontalGroup(
            AddingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        AddingAreaLayout.setVerticalGroup(
            AddingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout todopanelLayout = new javax.swing.GroupLayout(todopanel);
        todopanel.setLayout(todopanelLayout);
        todopanelLayout.setHorizontalGroup(
            todopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(todopanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddingArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(todopanelLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        todopanelLayout.setVerticalGroup(
            todopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todopanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddingArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Root.add(todopanel, java.awt.BorderLayout.LINE_START);

        getContentPane().add(Root, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    JFrame reportWindow = new JFrame();

    boolean firstTime = false;
    TaskManager taskManager = new TaskManager();
    Checkbox ch;
    
    
    public void retrieveCompletedTasksFromFile(String filename) {


        reportWindow.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        reportWindow.setSize(420, 420);
        reportWindow.getContentPane().setBackground(new Color(54, 48, 98));
        reportWindow.setLayout(new MigLayout());
        try (BufferedReader reader = new BufferedReader(new FileReader(filename))) {
            String line;
            while ((line = reader.readLine()) != null) {
                // Assume each line in the file is a task or data to display
                JLabel taskLabel = new JLabel(line);
                taskLabel.setFont(new Font("Times New Roman", Font.PLAIN, 20));
                taskLabel.setForeground(new Color(255, 255, 255));
                reportWindow.add(taskLabel, "wrap");
            }
        } catch (IOException e) {
            // Handle the exception, e.g., show an error message
            JLabel taskLabel = new JLabel("No Task");
            taskLabel.setBounds(0, 0, 100, 100);
            taskLabel.setFont(new Font("Times New Roman", Font.PLAIN, 20));
            taskLabel.setForeground(new Color(255, 255, 255));
            reportWindow.add(taskLabel, "wrap");
        }
        reportWindow.setVisible(true);

    }
    private void AddingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddingButtonActionPerformed
        // TODO add your handling code here:
        AddingArea.setLayout(new MigLayout("wrap"));
        AddingArea.setPreferredSize(AddingArea.getSize());

        if (!firstTime) {
            String Priority = PrioritySetter.getSelectedItem().toString();

            String MSSG = TaskInputer.getText() + " " + Priority;
            int priorityint = getPriority(Priority);

            ch = new Checkbox(MSSG);

            ch.setFont(new Font("Times New Roman", Font.PLAIN, 15));
            ch.setSize(new Dimension(30, 30));

            ch.setForeground(getPriorityColor(priorityint));
            taskManager.AddTask(MSSG, priorityint, ch);
            AddingArea.add(ch, "");

            AddingArea.validate();
            AddingArea.repaint();
            AddingArea.getParent().validate();
            AddingArea.getParent().repaint();
            firstTime = true;
            updatePomodoroUI(Task);
            updatePriorityUI();

            taskManager.saveTasksToFile("tasks.txt");
        } else {
            String Priority = PrioritySetter.getSelectedItem().toString();

            String MSSG = TaskInputer.getText() + " " + Priority;
            int priorityInt = getPriority(Priority);
            ch = new Checkbox(MSSG);

            ch.setForeground(getPriorityColor(priorityInt));

            ch.setFont(new Font("Times New Roman", Font.PLAIN, 15));
            ch.setSize(new Dimension(30, 30));

            taskManager.AddTask(MSSG, priorityInt, ch);
            AddingArea.add(ch, "");
            updatePriorityUI();
            updatePomodoroUI(Task);
            taskManager.saveTasksToFile("tasks.txt");

        }


    }//GEN-LAST:event_AddingButtonActionPerformed

    private void updatePriorityUI() {
        AddingArea.removeAll();

        Task currentTask = taskManager.getFrontTask();
        while (currentTask != null) {
            Color taskColor = getPriorityColor(currentTask.priority); // Get color based on priority
            currentTask.check.setForeground(taskColor);
            AddingArea.add(currentTask.check, "wrap"); // Add the checkbox to the UI
            currentTask = currentTask.next; // Move to the next task in the linked list
        }

        AddingArea.revalidate();
        AddingArea.repaint();
    }

    private Color getPriorityColor(int priority) {
        switch (priority) {
            case 1:
                return new Color(200, 14, 33);
            case 2:
                return new Color(227, 101, 29);
            case 3:
                return new Color(229, 210, 131);
            case 4:
                return new Color(190, 215, 84);
            default:
                return Color.BLACK;
        }
    }
    private void TaskInputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskInputerActionPerformed


    }//GEN-LAST:event_TaskInputerActionPerformed


    private void PrioritySetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrioritySetterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrioritySetterActionPerformed

    public boolean TimerSelected = false;
    Timer timer;
    boolean run = true;

    private void TimerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimerButtonActionPerformed
        // TODO add your handling code here

        TimerAddingPanel.removeAll();
        TimerSelected = true;

        TimerAddingPanel.setLayout(new MigLayout(""));
        JLabel TimerLabel = new JLabel();
        JButton SetButton = new JButton();
        JButton StartButton = new JButton();
        JButton PauseButton = new JButton();
        StartButton.setLabel("Start");
        PauseButton.setLabel("Pause");

        SetButton.setLabel("Set");
        SetButton.setFont(new Font("Times New Roman", Font.PLAIN, 20));

        TimerLabel.setText("00:00");
        TimerLabel.setFont(new Font("Times New Roman", Font.PLAIN, 30));
        TimerLabel.setForeground(Color.WHITE);
        TimerLabel.setVerticalAlignment(JLabel.CENTER);
        JLabel mins = new JLabel("MIN");
        mins.setFont(new Font("Times New Roman", Font.PLAIN, 15));
        mins.setForeground(Color.WHITE);

        JLabel Seconds = new JLabel("Secs");
        Seconds.setFont(new Font("Times New Roman", Font.PLAIN, 15));
        Seconds.setForeground(Color.WHITE);
        JTextField minsField = new JTextField("", 3);
        JTextField SecField = new JTextField("", 3);

        SetButton.setSize(PauseButton.getSize());

        TimerAddingPanel.add(TimerLabel, "center center,span,wrap");

        TimerAddingPanel.add(mins, "center center,gap 0");
        TimerAddingPanel.add(minsField, "grow 50,wrap");

        TimerAddingPanel.add(Seconds, ",center, gap 0");
        TimerAddingPanel.add(SecField, "grow 50,wrap");

        TimerAddingPanel.add(SetButton);

        TimerAddingPanel.add(StartButton);
        TimerAddingPanel.add(PauseButton);

        TimerAddingPanel.validate();
        TimerAddingPanel.repaint();
        SetButton.addActionListener(e -> {
            TimerLabel.setText(setTimerText(minsField, SecField));
        });

        StartButton.addActionListener(e
                -> {

            timer = new Timer(1000, new ActionListener() {
                int min = Integer.parseInt(minsField.getText());

                int sec = Integer.parseInt(SecField.getText());

                @Override
                public void actionPerformed(ActionEvent e) {

                    if (sec == 0) {
                        sec = 60;
                        min--;
                    }

                    if (min < 0) {
                        try {
                            playSound("alram.wav");
                            JOptionPane.showMessageDialog(rootPane, "Timer Done", "Stopped", 0);

                            min = 0;
                            sec = 0;

                            timer.stop();
                            run = false;
                        } catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (LineUnavailableException ex) {
                            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                    if (run) {
                        sec--;
                        if (sec < 10) {

                            if (min < 10) {
                                TimerLabel.setText("0" + min + ":" + "0" + sec);
                            } else {
                                TimerLabel.setText(min + ":" + "0" + sec);

                            }
                        } else {
                            TimerLabel.setText(min + ":" + sec);
                            if (min < 10) {
                                TimerLabel.setText("0" + min + ":" + sec);
                            } else {
                                TimerLabel.setText(min + ":" + sec);

                            }
                        }

                    }

                }

            });
            timer.start();
        });
        run = true;

        PauseButton.addActionListener(e
                -> {

            timer.stop();

        });


    }//GEN-LAST:event_TimerButtonActionPerformed
    public boolean firstRun = true;
    JLabel Task = new JLabel("");
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        if (taskManager.getFrontTask() == null) {
            JOptionPane.showMessageDialog(rootPane, "No Task Added");
            return;
        }
        TimerAddingPanel.removeAll();
        TimerAddingPanel.setSize(TimerAddingPanel.getSize());
        TimerAddingPanel.setLayout(new MigLayout(""));
        JLabel Timer = new JLabel();
        Task.setText("Currently Working On: " + taskManager.getFrontTask().task);
        JLabel BreakLabel = new JLabel("Break");
        JTextField BreakField = new JTextField();

        JButton start = new JButton("start");
        JButton stop = new JButton("stop");

        JTextField minField = new JTextField("");

        JTextField sessionField = new JTextField("");

        JLabel minLabel = new JLabel("Mins");
        JLabel SessionFieldLabel = new JLabel("Sessions");

        Timer.setText("00:00");

        Task.setFont(new Font("Times New Roman", Font.PLAIN, 15));
        Task.setForeground(Color.WHITE);

        Timer.setFont(new Font("Times New Roman", Font.PLAIN, 40));
        Timer.setForeground(Color.white);

        minLabel.setFont(new Font("Times New Roman", Font.PLAIN, 20));
        SessionFieldLabel.setFont(new Font("Times New Roman", Font.PLAIN, 20));
        minLabel.setForeground(Color.WHITE);
        SessionFieldLabel.setForeground(Color.WHITE);

        JLabel SessionTotal = new JLabel("0/0 Sessions");
        SessionTotal.setFont(new Font("Times New Roman", Font.PLAIN, 15));
        SessionTotal.setForeground(Color.white);
        BreakLabel.setFont(new Font("Times New Roman", Font.PLAIN, 20));
        BreakLabel.setForeground(Color.WHITE);

        TimerAddingPanel.add(Timer, "center center,span 2 3");
        TimerAddingPanel.add(SessionTotal);

        TimerAddingPanel.add(Task, "center center,span,wrap");

        TimerAddingPanel.add(minLabel, "gap 0");
        TimerAddingPanel.add(minField, "grow 50,wrap");

        TimerAddingPanel.add(SessionFieldLabel, "gap 0");
        TimerAddingPanel.add(sessionField, "grow 50,wrap");

        TimerAddingPanel.add(start);
        TimerAddingPanel.add(stop);
        TimerAddingPanel.add(BreakLabel, "gap 0");
        TimerAddingPanel.add(BreakField, "grow 50,wrap");

        start.addActionListener((e) -> {

            timer = new Timer(100, new ActionListener() {

                int min = 0;
                int sec = 0;
                int session = 0;
                int totalSession = 0;
                int breakTime = 0;
                int breakFlag = 0;

                int totalmin = 0;
                int totalBreak = 0;
                int breakCounter = 0;

                @Override
                public void actionPerformed(ActionEvent e) {

                    if (firstRun) {
                        min = Integer.parseInt(minField.getText());
                        sec = 60;
                        session = 0;
                        totalSession = Integer.parseInt(sessionField.getText());
                        breakTime = Integer.parseInt(BreakField.getText());
                        breakFlag = 0;

                        totalmin = min;
                        totalBreak = breakTime;

                        firstRun = false;
                        run = true;

                    }

                    if (sec == 0) {
                        sec = 60;
                        min--;

                    }

                    if (min < 0 && session == totalSession) {

                        SessionTotal.setText("0/0 Sessions");
                        try {
                            playSound("alram.wav");
                            JOptionPane.showMessageDialog(rootPane, "Timer Done", "Stopped", 0);

                        } catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (LineUnavailableException ex) {
                            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        min = 0;
                        sec = 0;

                        timer.stop();
                        run = false;
                        Timer.setForeground(Color.white);
                        session = 0;
                        totalSession = 0;
                        firstRun = true;

                    } else if (min < 0 && breakFlag == 0) {

                        try {
                            playSound("beep.wav");
                        } catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (LineUnavailableException ex) {
                            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        session++;
                        sec = 60;
                        breakFlag = 1;
                        breakCounter++;

                        if (breakCounter <= 4) {
                            min = breakTime;

                        } else {
                            min = breakTime * 2;
                            breakCounter = 0;

                        }

                    } else if (min < 0 && breakFlag == 1) {
                        try {
                            playSound("beep.wav");
                        } catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (LineUnavailableException ex) {
                            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        min = totalmin;
                        sec = 60;
                        breakFlag = 0;
                    }
                    if (run) {
                        if (breakFlag == 0) {
                            Timer.setForeground(new Color(255, 8, 0));
                            SessionTotal.setText(session + "/" + totalSession + " Sessions");
                            sec--;
                            if (sec < 10) {

                                if (min < 10) {
                                    Timer.setText("0" + min + ":" + "0" + sec);
                                } else {
                                    Timer.setText(min + ":" + "0" + sec);

                                }
                            } else {
                                Timer.setText(min + ":" + sec);
                                if (min < 10) {
                                    Timer.setText("0" + min + ":" + sec);
                                } else {
                                    Timer.setText(min + ":" + sec);

                                }
                            }

                        } else {
                            Timer.setForeground(new Color(38, 97, 156));
                            sec--;
                            if (sec < 10) {

                                if (min < 10) {
                                    Timer.setText("0" + min + ":" + "0" + sec);
                                } else {
                                    Timer.setText(min + ":" + "0" + sec);

                                }
                            } else {
                                Timer.setText(min + ":" + sec);
                                if (min < 10) {
                                    Timer.setText("0" + min + ":" + sec);
                                } else {
                                    Timer.setText(min + ":" + sec);

                                }
                            }
                        }

                    }

                }
            });
            timer.start();

        });
        run = true;

        stop.addActionListener(e -> {
            timer.stop();
            Timer.setText("00:00");
            Timer.setForeground(Color.WHITE);
            SessionTotal.setText("0/0 Sessions");
            firstRun = true;
            JOptionPane.showMessageDialog(rootPane, "Timer Stopped", "Stopped", 0);

        }
        );

        taskManager.getFrontTask().check.addItemListener(e
                -> {
            if (e.getStateChange() == 1) {
                updatePomodoroUI(Task);

            }

        });
        TimerAddingPanel.validate();
        TimerAddingPanel.repaint();

    }//GEN-LAST:event_jButton2ActionPerformed

    public void updatePomodoroUI(JLabel Task) {
        if (taskManager.getFrontTask() != null) {
            taskManager.getFrontTask().check.addItemListener(e
                    -> {
                if (e.getStateChange() == 1) {
                    updatePomodoroUI(Task);

                }

            });
            Task.setText("Currently Working On: " + taskManager.getFrontTask().task);

        } else {
            Task.setText("Currently Working On:" + " None");
        }
        TimerAddingPanel.validate();
        TimerAddingPanel.repaint();

    }

    public void ourDateTime() {

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        CurrentTimer.setForeground(Color.white);
        CurrentTimer.setFont(new Font("Times New Roman", Font.PLAIN, 16));
        CurrentTimer.setText(dtf.format(now));
    }

    private int getPriority(String Priority) {

        int index = 0;

        switch (Priority.toUpperCase()) {
            case "P1":
                index = 1;
                break;
            case "P2":
                index = 2;
                break;
            case "P3":
                index = 3;
                break;
            default:
                index = 4;
                break;
        }

        return index;

    }

    private String setTimerText(JTextField a, JTextField b) {
        try {
            if (a.getText() != null && b.getText() != null) {
                int aI = Integer.parseInt(a.getText());
                int bI = Integer.parseInt(b.getText());

                if (aI >= 0 && bI >= 0) {
                    // Convert hours to minutes and add to minutes
                    int totalMinutes = aI * 60 + bI;

                    // Limit minutes to 60
                    int minutes = totalMinutes % 60;

                    return String.format("%02d:%02d", aI, minutes);
                } else if (aI >= 0) {
                    return String.format("%02d:00", aI);
                } else if (bI >= 0) {
                    return String.format("00:%02d", bI);
                } else {
                    return "00:00";
                }
            } else {
                return "00:00";
            }
        } catch (NumberFormatException e) {
            // Handle the case where the input is not a valid integer
            JOptionPane.showMessageDialog(rootPane, "Numbers Only Please");
            return "00:00";
        }

    }

    public void playSound(String pathName) throws UnsupportedAudioFileException, LineUnavailableException, IOException {

        File file = new File(pathName);
        AudioInputStream audioStream = AudioSystem.getAudioInputStream(file);
        Clip clip = AudioSystem.getClip();
        clip.open(audioStream);

        clip.start();

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddingArea;
    private javax.swing.JButton AddingButton;
    private javax.swing.JPanel AddingPanel;
    private javax.swing.JLabel CurrentTimer;
    private javax.swing.JComboBox<String> PrioritySetter;
    private javax.swing.JPanel Root;
    private javax.swing.JTextField TaskInputer;
    private javax.swing.JPanel TimerAddingPanel;
    private javax.swing.JButton TimerButton;
    private javax.swing.JPanel TimerPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel todopanel;
    // End of variables declaration//GEN-END:variables
}
